<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

    use Laminas\Authentication\AuthenticationService;

    $auth = new AuthenticationService();
    

?>

<div class="container-fluid text-dark" style="background: #E0F2F7">
    <div class="container p-3 p-md-5">
        <h1>Welcome<?php 
                echo $auth->hasIdentity() ? (", ".$auth->getIdentity()->displayname.".") : "."; 
            ?>
            <br> ADMIN DASHBOARD</h1>
       
        <hr>

       
    </div>
</div>

<div class="container">
    <hr class="my-4">
</div>

<div class="row  row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card">
            <h2 class="card-header">Session</h2>
            <div class="card-body">
                <p>
                    Laminas Project is under active development. If you are
                    interested in following the development, you can check
                    <a href="https://getlaminas.org/blog/">Laminas dev blog</a>,
                    and <a href="https://github.com/issues?utf8=%E2%9C%93&amp;q=is:issue+org:laminas">Laminas issue
                        tracker</a>
                    (link requires a GitHub account). This is a great resource
                    for staying up to date with the latest developments!
                </p>

                <a class="btn btn-primary" href="https://getlaminas.org/" target="_blank">Laminas Project Portal
                    &raquo;</a>
            </div>
        </div>

    </div>

    <div class="col">
        <div class="card">
            <h2 class="card-header">Discover Modules</h2>
            <div class="card-body">
                <p>
                    Laminas MVC is a modular application.
                    You can find multiple compatible modules on packagist.
                </p>

                <a class="btn btn-primary"
                    href="https://packagist.org/?tags=module~zf2~zendframework~zend%20framework~zend%20framework%202~zf3~zf~zend~laminas"
                    target="_blank">
                    Explore Laminas Modules &raquo;
                </a>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h2 class="card-header">Help &amp; Support</h2>
            <div class="card-body">
                <p>
                    If you need any help or support while developing with Laminas,
                    you may reach us via <a href="https://laminas.dev/chat">chat</a> or
                    <a href="https://discourse.laminas.dev">forum</a>.
                    We'd love to hear any questions or feedback you may have
                    regarding any release.
                </p>

                <a class="btn btn-primary" href="https://laminas.dev/chat" target="_blank">Ping us on chat &raquo;</a>
            </div>
        </div>
    </div>
</div>