<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

    use Laminas\Authentication\AuthenticationService;

    $auth = new AuthenticationService();
    

?>

<div class="container-fluid text-dark" style="background: #E0F2F7">
    <div class="container p-3 p-md-5">
        <h1>Welcome<?php 
                echo $auth->hasIdentity() ? (", ".$auth->getIdentity()->displayname.".") : "."; 
            ?>
            <br> ADMIN DASHBOARD</h1>
       
        <hr>

       
    </div>
</div>

<div class="container">
    <hr class="my-4">
</div>

<div class="row  row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card">
            <h2 class="card-header">PRE-LOGIN</h2>
            <div class="card-body">
                <p>
                    Here you can see the $_SESSION data object and the Session Container Object
                </p>

                <a class="btn btn-primary" href="<?= $this->url('admin/session') ?>">View Data
                    &raquo;</a>
            </div>
        </div>

    </div>

    <div class="col">
        <div class="card">
            <h2 class="card-header">POST-LOGIN</h2>
            <div class="card-body">
                <p>
                    Here you can see the $_SESSION data object and the Session Container Object
                </p>

                <a class="btn btn-primary" href="<?= $this->url('admin/session') ?>">View Data
                    &raquo;</a>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h2 class="card-header">LOGOUT</h2>
            <div class="card-body">
                <p>
                    Click on the button below to destroy the Session
                </p>

                <a class="btn btn-primary" href="<?= $this->url('logout') ?>">Logout
                    &raquo;</a>
            </div>
        </div>
    </div>
</div>